#!/bin/bash
set +x
set -e

BASE_DIR=`cd "$(dirname "$0")";pwd`
cd "$BASE_DIR"

config=config
[ -r $config ] || config=$config.sample
source $config

# Import the generated certificate into keystore
keytool -import -alias $alias \
-file generated/$CN.crt \
-keystore generated/$CN.pfx \
-storepass ${storepass} \
-keypass ${keypass}
