= Scripts to generate and install HTTPS certificate for gs-rest-service
Paulo Jerônimo <paulojeronimo@gmail.com>; {localdatetime}
:icons: font
:toc:
:numbered:

== Generate a certificate signing request (CSR)

To generate a CSR, type:

----
$ ./generate-csr
----

The link:generate-csr[] script (see it for details) will generate two files:

----
$ tree generated
generated
|-- gs-rest-service.paulojeronimo.com.csr
`-- gs-rest-service.paulojeronimo.com.pfx

0 directories, 2 files
----

The file `gs-rest-service.paulojeronimo.com.pfx` is the keystore in `PKCS#12` format.

The file `gs-rest-service.paulojeronimo.com.csr` is the CSR. You must send it to the the certificate authority (CA) in order to receive your certificate (CRT).

== Install a certificate

After receive the certificate files from your CA, create a directory `received-from-ca` and put theses files into it, like the following example:

----
$ tree received-from-ca/
received-from-ca/
|-- cacert.pem
`-- gs-rest-service.paulojeronimo.com.crt

0 directories, 2 files
----

The CA root certificate (`cacert.pem`) needs to be imported into the keystore by using the script link:import-cacert[]:

----
$ ./import-cacert
----

After that, you need to import your certificate (`gs-rest-service.paulojeronimo.com.crt`) by calling the script link:import-crt[]:

----
$ ./import-crt
----

== Configure gs-rest-service to use the certificate

The following call to link:app[] script makes the adjustments needed in `gs-rest-service` project in order to turn it capable to receive HTTPS requests.

----
$ ./app install-https
----
